export default function TermsPage() {
  return (
    <div style={{ fontFamily: 'monospace', background: '#060a0f', color: '#e6edf3', minHeight: '100vh', padding: '80px 40px' }}>
      <div style={{ maxWidth: 800, margin: '0 auto' }}>

        {/* Logo */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 40 }}>
          <div style={{ width: 40, height: 40, borderRadius: 10, background: 'linear-gradient(135deg, #C9A84C, #E8D08C)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20, fontWeight: 700, color: '#060a0f' }}>C</div>
          <div>
            <div style={{ fontSize: 16, fontWeight: 700 }}><span style={{ color: '#C9A84C' }}>CapitalMarket</span> Pro</div>
            <div style={{ fontSize: 11, color: '#484f58' }}>Terms & Conditions</div>
          </div>
        </div>

        <h1 style={{ fontSize: 32, fontWeight: 800, color: '#e6edf3', marginBottom: 8 }}>Terms & Conditions</h1>
        <p style={{ fontSize: 13, color: '#484f58', marginBottom: 40 }}>Last updated: January 1, 2025 · Effective immediately upon account creation</p>

        {[
          {
            title: '1. Acceptance of Terms',
            content: `By creating an account or using CapitalMarket Pro ("the Platform"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, you may not access or use our services. These terms constitute a legally binding agreement between you and CapitalMarket Pro.`,
          },
          {
            title: '2. Nature of Services',
            content: `CapitalMarket Pro provides a unified investment management platform that facilitates access to cryptocurrency trading, stock market investments, and affiliate marketing services. The Platform operates as an intermediary and does not guarantee specific returns or profits. All trading activities involve substantial risk of loss.`,
          },
          {
            title: '3. Regulatory Fees & Charges',
            content: `The following fees apply to all accounts on CapitalMarket Pro:

• Deposit Fee: 0% — No fees on incoming deposits
• Withdrawal Processing Fee: 0.5% of withdrawal amount (minimum $2.00)
• Trading Commission: 0.1% per executed trade
• Inactivity Fee: $10/month after 6 months of account inactivity
• Wire Transfer Fee: $25 per outgoing wire transfer
• Regulatory Compliance Fee: 0.05% annually on account balance (charged quarterly)
• Currency Conversion Fee: 1.5% on all non-USD transactions
• Signal Subscription: Billed monthly as per selected plan (Basic $29, Pro $79, Elite $149, VIP $299)
• Account Verification Fee: Free for standard KYC; $15 for expedited processing
• Tax Reporting Fee: $25 annually for tax document generation (1099 forms)

All fees are subject to change with 30 days written notice. Fees are automatically deducted from your account balance.`,
          },
          {
            title: '4. Deposits & Withdrawals',
            content: `Deposits are accepted via Bitcoin (BTC) and other supported cryptocurrencies. Minimum deposit amount is $100 USD equivalent. Withdrawal requests are processed within 24-48 business hours, subject to compliance review. CapitalMarket Pro reserves the right to delay or suspend withdrawals pending verification or investigation of suspicious activity. All withdrawals are subject to the fees outlined in Section 3.`,
          },
          {
            title: '5. Trading Signals Disclaimer',
            content: `Trading signals provided by CapitalMarket Pro are generated by automated algorithms and are for informational purposes only. They do not constitute financial advice or a guarantee of profit. Past signal performance is not indicative of future results. Users acknowledge that trading based on signals carries inherent risk and that CapitalMarket Pro is not liable for any losses incurred. Signal accuracy rates are based on historical backtesting and may differ in live market conditions.`,
          },
          {
            title: '6. Risk Disclosure',
            content: `Trading financial instruments including cryptocurrencies, stocks, and derivatives carries a high level of risk and may not be suitable for all investors. You may lose some or all of your invested capital. Before trading, carefully consider your investment objectives, level of experience, and risk appetite. CapitalMarket Pro does not guarantee any minimum returns and is not responsible for any losses incurred as a result of using the Platform.`,
          },
          {
            title: '7. KYC & AML Compliance',
            content: `CapitalMarket Pro complies with applicable Know Your Customer (KYC) and Anti-Money Laundering (AML) regulations. All users are required to complete identity verification before accessing full platform features. We reserve the right to request additional documentation at any time. Accounts suspected of fraudulent activity will be suspended pending investigation and may be reported to relevant authorities.`,
          },
          {
            title: '8. Privacy & Data Protection',
            content: `We collect and process personal data in accordance with our Privacy Policy. By using the Platform, you consent to the collection, storage, and processing of your personal information for account management, compliance, and service improvement purposes. We do not sell your personal data to third parties. Data may be shared with regulatory authorities as required by law.`,
          },
          {
            title: '9. Account Termination',
            content: `CapitalMarket Pro reserves the right to suspend or terminate any account at its sole discretion, including but not limited to violations of these Terms, suspected fraudulent activity, or regulatory requirements. Upon termination, any remaining balance (minus applicable fees) will be returned to the user within 30 business days, subject to compliance clearance.`,
          },
          {
            title: '10. Limitation of Liability',
            content: `To the maximum extent permitted by law, CapitalMarket Pro shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Platform, including but not limited to trading losses, data loss, or service interruptions. Our total liability to you shall not exceed the total fees paid by you in the 12 months preceding the claim.`,
          },
          {
            title: '11. Governing Law',
            content: `These Terms shall be governed by and construed in accordance with applicable financial regulations. Any disputes shall be resolved through binding arbitration. By using the Platform, you waive any right to a jury trial and agree to resolve disputes on an individual basis rather than as part of a class action.`,
          },
          {
            title: '12. Contact Information',
            content: `For questions regarding these Terms, please contact us at:
            
Email: legal@capitalmarketpro.com
Support: support@capitalmarketpro.com
Address: CapitalMarket Pro Financial Services`,
          },
        ].map((section, i) => (
          <div key={i} style={{ marginBottom: 36, paddingBottom: 36, borderBottom: '1px solid #161b22' }}>
            <h2 style={{ fontSize: 16, fontWeight: 700, color: '#C9A84C', marginBottom: 12 }}>{section.title}</h2>
            <p style={{ fontSize: 13, color: '#8b949e', lineHeight: 2, whiteSpace: 'pre-line' }}>{section.content}</p>
          </div>
        ))}

        <div style={{ background: 'rgba(201,168,76,0.06)', border: '1px solid rgba(201,168,76,0.2)', borderRadius: 12, padding: 20, marginTop: 20 }}>
          <div style={{ fontSize: 13, fontWeight: 600, color: '#C9A84C', marginBottom: 8 }}>⚖ Legal Notice</div>
          <div style={{ fontSize: 12, color: '#8b949e', lineHeight: 1.8 }}>
            CapitalMarket Pro is a private investment platform. Trading involves risk. Please read all terms carefully before using our services. By continuing to use this platform, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions.
          </div>
        </div>

        <div style={{ textAlign: 'center', marginTop: 40, fontSize: 12, color: '#484f58' }}>
          © 2025 CapitalMarket Pro. All rights reserved.
        </div>
      </div>
    </div>
  )
}